### ISSUE TITLE
显示多级子文档树

### ISSUE THREAD

**Issue by gaoluji** [frostime/sy-docs-flow#10]
![image](https://github.com/frostime/sy-docs-flow/assets/139356383/0664c869-f635-4209-a2cf-82ef55bf0c3e)
![image](https://github.com/frostime/sy-docs-flow/assets/139356383/1997c252-6c46-430c-a17c-27f81359299f)
如图，子文档只能显示一级，不知是否可以显示子文档的子文档
关于显示的建议，是否可以在显示页面改变子文档的页宽度来显示层级
![无标题](https://github.com/frostime/sy-docs-flow/assets/139356383/f32c6ec0-8d86-49cf-9920-9ae0695dbd0d)
由于有了层级，还可以进行对所属的子文档进行折叠功能

**Comment by frostime** [comment]
多显示几层子文档应该是可以的，但是后面那个改变页面宽度的需求和现有的程序逻辑设计有冲突，不太好改变。
