### ISSUE TITLE
关于快速打开嵌入块文档流

### ISSUE THREAD

**Issue by winter60** [frostime/sy-docs-flow#20]
这个插件是我今天最开心的事了，太感谢大佬了

如果有时间可以考虑一下下面的建议：
1. 可以通过块菜单，打开嵌入块的文档流。
2. 可以通过鼠标或键盘的操作（如ctrl+shift+单击嵌入块），打开嵌入块的文档流。

**Comment by frostime** [comment]
方案一可能比较容易一点，键盘不好定位到特定的块
