### ISSUE TITLE
可以通过siyuan:超链接直接打开某个文档流tab页

### ISSUE THREAD

**Issue by winter60** [frostime/sy-docs-flow#21]
rt.
大佬太牛逼了，完全符合去年提的功能。
[支持自定义查询的滚动式页面提议 (草稿)](https://pipe.b3log.org/blogs/kobi/articles/2022/06/08/1654692267425)

**Comment by frostime** [comment]
v0.6.0 版本已经解决

![Uploading dfb440e547d71337de2045c310ff9b38.gif…]()
