### ISSUE TITLE
移动端反馈情况

### ISSUE THREAD

**Issue by winter60** [frostime/sy-docs-flow#29]
1. 保存的规则与移动端似乎没有同步，移动端仍然是空的。
2. 输入的sql和pc上一样，但仍然显示`无法匹配对应的文档`

**Comment by frostime** [comment]
移动端我这边很少使用，确实没怎么测试过。

按理说，保存的规则存放在 `data\storage\petal\sy-docs-flow\saved-rule.json` 文件里，如果没有读取可能是同步问题？

## 移动端适配问题

我刚刚过去看了一下移动端，发现这个插件和移动端可能还真的不太适配。文档流插件高度依赖 tab 标签，但是移动端的结构里压根没有 tab 标签页这个东西。。。

我这边测试是根本打不开文档流的页面，不知道你那边是不是也是这样。

这个估计不好解决，我想干脆不做移动端适配算了。。。

## SQL

你说的无法匹配到文档的 SQL 是啥样子的？能不能发给我看？

**Comment by winter60** [comment]
@frostime 又测试了下，sql复制少了，现在只是打不开了。谢谢大佬。移动端太麻烦还是不适配了吧
