### ISSUE TITLE
能为文档树右键菜单提供“子文档/文档树”文档流功能吗？

### ISSUE THREAD

**Issue by XinLi0111** [frostime/sy-docs-flow#30]

**Comment by frostime** [comment]
目前应该还不行，思源没有提供点击右键菜单的 API 接口，我后面可以问一下开发者能不能加一下这个事件

**Comment by XinLi0111** [comment]
嗯嗯，另外您觉得提供 1-2 个快捷键直接打开提前设置好的文档流视图会有助于提升使用体验不。

个人使用过程中希望能比较方便的切换每日笔记或每日笔记文档流。其实，直接一直使用文档流好像也可以，但是打开的时候不是太方便。看到有个 issue 提的和每日笔记进行结合，不知道会不会有新的呈现方式。

**Comment by frostime** [comment]
> 嗯嗯，另外您觉得提供 1-2 个快捷键直接打开提前设置好的文档流视图会有助于提升使用体验不。
> 
> 个人使用过程中希望能比较方便的切换每日笔记或每日笔记文档流。其实，直接一直使用文档流好像也可以，但是打开的时候不是太方便。看到有个 issue 提的和每日笔记进行结合，不知道会不会有新的呈现方式。

快捷键也可以做考虑。但主要问题是我这段时间个人事情很多，不想前几个月能抽出来大量时间写插件，所以更新频率很低，还请理解见谅。😂

**Comment by XinLi0111** [comment]
> 快捷键也可以做考虑。但主要问题是我这段时间个人事情很多，不想前几个月能抽出来大量时间写插件，所以更新频率很低，还请理解见谅。😂

能使用您的插件已经很感谢了，祝您工作生活都顺利！期待之后的更新。
