### ISSUE TITLE
每次动态加载下一批数据，似乎滚动条就会回到顶部

### ISSUE THREAD

**Issue by winter60** [frostime/sy-docs-flow#48]
期待不改变滚动条当前位置。

**Comment by frostime** [comment]
不改变滚动条位置是不可能的，动态加载的机理是每次加载固定数量的文档；再加载新一批的数据的时候，会丢弃掉旧的一批数据，不然的话加载到最后文档 Protyle 太多会非常卡。
![image](https://github.com/frostime/sy-docs-flow/assets/27268127/919a38e6-0733-45c3-a358-1aab8056304e)

滚动条更新后的位置取决于这两个配置项的取值。比如这里容量和增量分别为 7 和 4 ，就意味着拉到最下面之后，会新加载 4 篇文章，并维持总量 7 篇，这样更新后滚动条的位置总是会移动到大概中间的位置。

**Comment by frostime** [comment]
我先关了，有疑问可以在这继续问

**Comment by winter60** [comment]
确实，调整了加载容量和增量配置就好了
