### ISSUE TITLE
「显示文档树」的顺序改为深度优先

### ISSUE THREAD

**Issue by rsreland** [frostime/sy-docs-flow#53]
![未命名绘图](https://github.com/frostime/sy-docs-flow/assets/1543134/404b0570-4e48-4256-b3e9-bee005736d2e)

如图，现在是显示顺序是第二栏的样子，希望设置成第三栏的样子。

另外，现在的显示顺序按照文档初次创建时的顺序显示，而不是用户在目录中调整后的顺序。

**Comment by frostime** [comment]
是「显示文档树」的规则是吗？

**Comment by rsreland** [comment]
> 是「显示文档树」的规则是吗？

对，是文档树。
