### ISSUE TITLE
能否添加一个在页签右侧打开的功能？

### ISSUE THREAD

**Issue by Reader2024** [frostime/sy-docs-flow#56]
我会用文档流插件的反链功能，相当于把文档流当做第二个反链面板来使用。

在这种场景下，通常是需要把文档流的反链面板打开在页签右侧，以此对照进行拖拽操作。

实现可参考网页视图插件。

![image](https://github.com/frostime/sy-docs-flow/assets/167050853/6f23cc69-f113-4f65-ae3b-80a5ac597a68)

**Comment by frostime** [comment]
从功能上可以。但是这么搞菜单按钮会变复杂化吧。

文档流的 tab 页签也是可以拖动的，直接拖到右边分屏就可以了啊。
![image](https://github.com/frostime/sy-docs-flow/assets/27268127/f5ba18f6-56b9-4473-b909-20776a686d3e)

如果要增加按钮，就会让本来一级菜单就可以解决的功能不得不拓展出二级菜单出来，我觉得性价比不高。

**Comment by frostime** [comment]
您好，请问你还有没有什么想法？

我个人意见是不赞同加入额外的按钮。如果你没有什么别的意见，我就先关闭这个 issue 了。

**Comment by frostime** [comment]
没有回复的话，我就默认先关闭这个 issue 了，如果还有其他的意见可以继续在这个 issue 下面提出。
