### ISSUE TITLE
插件中开启“只读模式”时，「文档反链」会显示全文而非内容块

### ISSUE THREAD

**Issue by QMike0** [frostime/sy-docs-flow#65]
如题，当插件中开启“只读模式”时，通过插件进入的「文档反链」会显示反链对应的文档全文，而非反链对应的内容块，展示如下：
关闭“只读模式”时，正常显示反链对应的内容块：
![recording](https://github.com/frostime/sy-docs-flow/assets/43239563/a76b5b51-eee8-4503-a795-acf90a431fec)

开启“只读模式”后，转而显示反链对应的内容块所在全文，无法只定位到相应内容块
![recording](https://github.com/frostime/sy-docs-flow/assets/43239563/9a4e66a7-3c02-406a-92e4-e1afe526c4df)

**Comment by frostime** [comment]
我尝试了一下，准确来说是所有规则下，只要开启只读模式，就会全览文档。

这个不确定能不能解决。
目前文档流插件的「只读模式」对应的是思源的「预览模式」；而在思源里面同样存在类似的问题——当开启「预览模式」之后，对文档的聚焦就会失效，只能显示完整的文档内容。

**Comment by QMike0** [comment]
嗯嗯好吧，那就先不开只读模式了

**Comment by frostime** [comment]
> 嗯嗯好吧，那就先不开只读模式了

我先关了，如果还有问题可以继续在这里回复。
