### ISSUE TITLE
“日记”模式无法检索出全部日记

### ISSUE THREAD

**Issue by RemWisteria** [frostime/sy-docs-flow#69]
只能显示部分日记至文档流中，某个日期之前的日记无法被检测到。
如图，在2023-12-20之前的日记均未显示至文档流中。
![QQ20240828-231501](https://github.com/user-attachments/assets/c10f625c-b16f-4bc3-aafd-82332bfa2ffc)

**Comment by frostime** [comment]
这个 issue 先 close 了，如果还有问题可以继续在这回复。

**Comment by RemWisteria** [comment]
> 日记的查询是基于思源的日记属性的，这个特性大概也就是在 23 年引入的，可能你更早的日记没有这个文档属性。
> 
> ![image](https://private-user-images.githubusercontent.com/27268127/362369207-5fdd3907-9582-4a41-9079-9e0e7807c3f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjMwNDcsIm5iZiI6MTcyNjEyMjc0NywicGF0aCI6Ii8yNzI2ODEyNy8zNjIzNjkyMDctNWZkZDM5MDctOTU4Mi00YTQxLTkwNzktOWUwZTc4MDdjM2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA2MzIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZGQ1YWZkMmZmZjk4MTI2N2E0NmI2ZTQ1MDQ2OTNkOTQ3NTRmNmQ5MWRmMTMwOGQ2OWRlMzMxZTkzZThjYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j__9hx6p3Z9dFpUFEhlg3A7167c8YX_q2zG60tByxo0)
> 
> 如果是这个问题导致的话，你可以下载一下「今日笔记」插件，他里面提供了一个补充日记属性的功能。 ![image](https://private-user-images.githubusercontent.com/27268127/362369666-fe8f0ea8-3ab4-421f-8056-636b3f3e8981.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjMwNDcsIm5iZiI6MTcyNjEyMjc0NywicGF0aCI6Ii8yNzI2ODEyNy8zNjIzNjk2NjYtZmU4ZjBlYTgtM2FiNC00MjFmLTgwNTYtNjM2YjNmM2U4OTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA2MzIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzM2RjM2QwODA4ZmY1ODZjMGY4YjZlMDY3M2Y0Nzk5NmM0Y2EyYjQxNGRhYTMxNWM1MWRiNGUxN2U4MzlhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZkOShreIEur2NBroSJxnCR1KtxhD7ESpcfQyaYpEhhA)

按照你提供的方法后，以前的日记可以被检索到了，谢谢。
