### ISSUE TITLE
嵌入块sql带有 limit 0,5 会提示No matching docs found.

### ISSUE THREAD

**Issue by winter60** [frostime/sy-docs-flow#71]

**Comment by winter60** [comment]
发现不支持逗号后面那个数字

**Comment by frostime** [comment]
这个好像不是插件的问题，发 SQL 请求也会出现这种。

你可以换一个用法： limit 5 offset 0;

![image](https://github.com/user-attachments/assets/8835fae6-34d6-4871-ab77-50f7cc20155b)

**Comment by winter60** [comment]
> limit 5 offset 0; 

这个可以，感谢。单独在sqlite数据库执行或在嵌入块使用却没问题，好奇怪，谢了，关闭了哈
